# See reference docs at
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: ci
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # Use alternative image when running on GitHub workflows CI to avoid potential
  # rate limiting when executing jobs in parallel: they can't cache docker images
  # and always pull.
  #
  # To update this image, generate a personal token with write:packages scope
  # on https://github.com/settings/tokens and authenticate yourself locally with
  # "docker login ghcr.io -u <github-username>" using the
  # newly generated token as password.
  # Once logged in, tag an new image:
  #   docker tag shiftcrypto/bitbox-wallet-app:VERSION \
  #     ghcr.io/bitboxswiss/bitbox-wallet-app-ci:VERSION
  # and push as usual:
  #   docker push ghcr.io/bitboxswiss/bitbox-wallet-app-ci:VERSION
  # Lastly, update the next line to use the newly pushed image version.
  # See docs for more details:
  # https://docs.github.com/en/packages/guides/pushing-and-pulling-docker-images
  #
  # Keep this in sync with default in scripts/github-ci.sh.
  CI_IMAGE: ghcr.io/bitboxswiss/bitbox-wallet-app-ci:25
  GITHUB_BUILD_DIR: ${{github.workspace}}

jobs:
  report-artifacts:
    runs-on: ubuntu-22.04
    if: ${{ !cancelled() }}
    steps:
      - name: Create short sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - if: job.status == 'success'
        uses: mattermost/action-mattermost-notify@master
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MM_WEBHOOK_URL }}
          PAYLOAD: |-
            {
              "text": "**New artifacts built**\n([${{ github.repository }}](https://github.com/${{ github.repository }}), branch: ${{ github.ref_name }}, commit: ${{ steps.vars.outputs.sha_short }})\n* 1\n* 2",
              "icon_emoji": "white_check_mark"
            }

      - if: job.status != 'failure'
        uses: mattermost/action-mattermost-notify@master
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MM_WEBHOOK_URL }}
          PAYLOAD: |-
            {
              "text": "**Oh no! [${{ steps.vars.outputs.sha_short }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) failed to build.**\n[Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) failed.",
              "icon_emoji": "warning"
            }
