# See reference docs at
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: ci
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # Use alternative image when running on GitHub workflows CI to avoid potential
  # rate limiting when executing jobs in parallel: they can't cache docker images
  # and always pull.
  #
  # To update this image, generate a personal token with write:packages scope
  # on https://github.com/settings/tokens and authenticate yourself locally with
  # "docker login ghcr.io -u <github-username>" using the
  # newly generated token as password.
  # Once logged in, tag an new image:
  #   docker tag shiftcrypto/bitbox-wallet-app:VERSION \
  #     ghcr.io/bitboxswiss/bitbox-wallet-app-ci:VERSION
  # and push as usual:
  #   docker push ghcr.io/bitboxswiss/bitbox-wallet-app-ci:VERSION
  # Lastly, update the next line to use the newly pushed image version.
  # See docs for more details:
  # https://docs.github.com/en/packages/guides/pushing-and-pulling-docker-images
  #
  # Keep this in sync with default in scripts/github-ci.sh.
  CI_IMAGE: ghcr.io/bitboxswiss/bitbox-wallet-app-ci:25
  GITHUB_BUILD_DIR: ${{github.workspace}}

jobs:
  report-artifacts:
    runs-on: ubuntu-22.04
    if: ${{ !cancelled() }}
    steps:
      - if: job.status == 'success'
        uses: mattermost/action-mattermost-notify@master
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MM_WEBHOOK_URL }}
          MATTERMOST_ICON_URL: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0iIzAwMDAwMCIgdmlld0JveD0iMCAwIDI1NiAyNTYiPjxwYXRoIGQ9Ik0xNzAuODMsMTAxLjE3YTQsNCwwLDAsMSwwLDUuNjZsLTU2LDU2YTQsNCwwLDAsMS01LjY2LDBsLTI0LTI0YTQsNCwwLDAsMSw1LjY2LTUuNjZMMTEyLDE1NC4zNGw1My4xNy01My4xN0E0LDQsMCwwLDEsMTcwLjgzLDEwMS4xN1pNMjI4LDEyOEExMDAsMTAwLDAsMSwxLDEyOCwyOCwxMDAuMTEsMTAwLjExLDAsMCwxLDIyOCwxMjhabS04LDBhOTIsOTIsMCwxLDAtOTIsOTJBOTIuMSw5Mi4xLDAsMCwwLDIyMCwxMjhaIj48L3BhdGg+PC9zdmc+
          TEXT: |
            New build artifacts from `master` branch of ${{ github.repository }}.

      - if: job.status != 'failure'
        uses: mattermost/action-mattermost-notify@master
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MM_WEBHOOK_URL }}
          MATTERMOST_ICON_URL: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0iIzAwMDAwMCIgdmlld0JveD0iMCAwIDI1NiAyNTYiPjxwYXRoIGQ9Ik0yMzMuMzQsMTkwLjA5LDE0NS44OCwzOC4yMmgwYTIwLjc1LDIwLjc1LDAsMCwwLTM1Ljc2LDBMMjIuNjYsMTkwLjA5YTE5LjUyLDE5LjUyLDAsMCwwLDAsMTkuNzFBMjAuMzYsMjAuMzYsMCwwLDAsNDAuNTQsMjIwSDIxNS40NmEyMC4zNiwyMC4zNiwwLDAsMCwxNy44Ni0xMC4yQTE5LjUyLDE5LjUyLDAsMCwwLDIzMy4zNCwxOTAuMDlaTTIyNi40LDIwNS44YTEyLjQ3LDEyLjQ3LDAsMCwxLTEwLjk0LDYuMkg0MC41NGExMi40NywxMi40NywwLDAsMS0xMC45NC02LjIsMTEuNDUsMTEuNDUsMCwwLDEsMC0xMS43MkwxMTcuMDUsNDIuMjFhMTIuNzYsMTIuNzYsMCwwLDEsMjEuOSwwTDIyNi40LDE5NC4wOEExMS40NSwxMS40NSwwLDAsMSwyMjYuNCwyMDUuOFpNMTI0LDE0NFYxMDRhNCw0LDAsMCwxLDgsMHY0MGE0LDQsMCwwLDEtOCwwWm0xMiwzNmE4LDgsMCwxLDEtOC04QTgsOCwwLDAsMSwxMzYsMTgwWiI+PC9wYXRoPjwvc3ZnPg==
          TEXT: |
            Oh, oh, CI for ${{ github.repository }} is broken.
            [Pipeline](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) failed.
