# See reference docs at
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: ci
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # Use alternative image when running on GitHub workflows CI to avoid potential
  # rate limiting when executing jobs in parallel: they can't cache docker images
  # and always pull.
  #
  # To update this image, generate a personal token with write:packages scope
  # on https://github.com/settings/tokens and authenticate yourself locally with
  # "docker login ghcr.io -u <github-username>" using the
  # newly generated token as password.
  # Once logged in, tag an new image:
  #   docker tag shiftcrypto/bitbox-wallet-app:VERSION \
  #     ghcr.io/bitboxswiss/bitbox-wallet-app-ci:VERSION
  # and push as usual:
  #   docker push ghcr.io/bitboxswiss/bitbox-wallet-app-ci:VERSION
  # Lastly, update the next line to use the newly pushed image version.
  # See docs for more details:
  # https://docs.github.com/en/packages/guides/pushing-and-pulling-docker-images
  #
  # Keep this in sync with default in scripts/github-ci.sh.
  CI_IMAGE: ghcr.io/bitboxswiss/bitbox-wallet-app-ci:25
  GITHUB_BUILD_DIR: ${{github.workspace}}

jobs:
  test-lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone the repo
        with:
          submodules: recursive
        uses: actions/checkout@v4
      - name: Run CI script
        # The script also runs golang-ci but it's ok: doesn't take too long and may be useful
        # to keep its linter errors in this log, too.
        run: ./scripts/github-ci.sh ci
        env:
          OS_NAME: linux
  android:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4
      - name: Enable caching
        uses: actions/cache@v4
        with:
          key: ${{runner.os}}-android
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
      - name: Build Android
        run: ./scripts/github-ci.sh android
        env:
          OS_NAME: linux
      - name: Upload APK
        id: upload-app
        uses: actions/upload-artifact@v4
        with:
          path: frontends/android/BitBoxApp/app/build/outputs/apk/debug/app-debug.apk
          name: BitBoxApp-android-${{github.sha}}.apk
  qt-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Qt-Linux
        run: ./scripts/github-ci.sh qt-linux
        env:
          OS_NAME: linux
      - name: Upload AppImage
        id: upload-app-app-image
        uses: actions/upload-artifact@v4
        with:
          path: frontends/qt/build/linux/BitBoxApp-*.AppImage
          name: BitBoxApp-linux-${{github.sha}}.AppImage
      - name: Upload deb
        id: upload-app-deb
        uses: actions/upload-artifact@v4
        with:
          path: frontends/qt/build/linux/bitbox_*.deb
          name: BitBoxApp-linux-${{github.sha}}.deb
      - name: Upload rpm
        id: upload-app-rpm
        uses: actions/upload-artifact@v4
        with:
          path: frontends/qt/build/linux/bitbox-*.rpm
          name: BitBoxApp-linux-${{github.sha}}.rpm
  macos:
    runs-on: macos-13
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Qt
        # Qt modules: Not sure why we need qtpositioning - app compilation fails without. Maybe the webengine depends on it.
        # qtpositioning depends on qtserialport.
        # qtwebchannel is for the JS/backend bridge.
        # qtwebengine is for rendering the frontend.
        run: |
          pip install aqtinstall
          aqt install-qt mac desktop 6.2.4 --modules qtpositioning qtserialport qtwebchannel qtwebengine --outputdir ~/Qt
          echo "$HOME/Qt/6.2.4/macos/bin" >> $GITHUB_PATH
          echo "$HOME/Qt/6.2.4/macos/libexec" >> $GITHUB_PATH
      - name: Build macOS app
        run: >
          ./scripts/github-ci.sh qt-osx;
        env:
          OS_NAME: osx
      - name: Archive app
        run: >
          pushd ~/go/src/github.com/BitBoxSwiss/bitbox-wallet-app/frontends/qt/build/osx;
          ditto -c -k --keepParent BitBox.app ${{github.workspace}}/BitBoxApp-macos.zip;
          popd;
      - name: Upload app
        id: upload-app
        uses: actions/upload-artifact@v4
        with:
          path: BitBoxApp-macos.zip
          name: BitBoxApp-macos-${{github.sha}}.zip
  ios:
    runs-on: macos-14
    env:
      GO_SRC_DIR: src/github.com/BitBoxSwiss/bitbox-wallet-app
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          # Take Go version to install from go.mod.
          go-version-file: 'go.mod'
      - name: Set GOPATH
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
      - name: Copy repo to GOPATH
        # This is needed as gomobile is still unaware of go modules, so the repo must be in GOPATH
        run: |
          mkdir -p $GOPATH/$(dirname $GO_SRC_DIR)
          cp -a ${{github.workspace}} $GOPATH/$(dirname $GO_SRC_DIR)
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Build iOS app
        run: |
          make gomobileinit
          (cd $GOPATH/$GO_SRC_DIR; make ios)

  report-artifacts:
    runs-on: ubuntu-22.04
    needs: [android, qt-linux, macos, ios]
    if: ${{ !cancelled() }}
    steps:
      - if: job.status == 'success'
        uses: mattermost/action-mattermost-notify@master
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MM_WEBHOOK_URL }}
          MATTERMOST_ICON_URL: https://uxwing.com/wp-content/themes/uxwing/download/resize.php?size=512x512&file=check-mark-circle-line-icon.png&category_slug=checkmark-cross
          TEXT: |
            New build artifacts from `master` branch of ${{ github.repository }}.
            * Android - [Download](${{needs.android.steps.upload-app.outputs.artifact-url}})
            * Linux - [AppImage](${{needs.qt-linux.steps.upload-app-app-image.outputs.artifact-url}}) [DEB](${{needs.qt-linux.steps.upload-app-deb.outputs.artifact-url}}) [RPM](${{needs.qt-linux.steps.upload-app-rpm.outputs.artifact-url}})
            * MacOS - [Download](${{needs.macos.steps.upload-app.outputs.artifact-url}})

      - if: job.status == 'failure'
        uses: mattermost/action-mattermost-notify@master
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MM_WEBHOOK_URL }}
          MATTERMOST_ICON_URL: https://uxwing.com/wp-content/themes/uxwing/download/resize.php?size=512x512&file=check-mark-circle-line-icon.png&category_slug=checkmark-cross
          TEXT: |
            Oh, oh, CI for ${{ github.repository }} is broken.
            [Pipeline](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) failed.
